name: VelocityEssentials-Backend
version: ${project.version}
main: com.velocityessentials.backend.VelocityEssentialsBackend
api-version: "1.21"
load: STARTUP
loadbefore:     # force us to load first
  - ChatFeelings
author: hxrry27
description: Paper companion for VelocityEssentials
softdepend: [PlaceholderAPI]

commands:
  afk:
    description: Toggle AFK status or set AFK with a message
    usage: /<command> [message]
    permission: velocityessentials.afk
  chat:
    description: Manage chat channels
    usage: /chat [channel|list]
    aliases: [ch]

permissions:
  velocityessentials.afk:
    description: Allows use of /afk command
    default: true
  velocityessentials.afk.message:
    description: Allows setting custom AFK messages with /afk <message>
    default: true
  velocityessentials.afk.exempt:
    description: Exempt from automatic AFK
    default: op
  velocityessentials.afk.kickexempt:
    description: Exempt from being kicked when AFK
    default: op